"""empty message

Revision ID: 4723b1c10c01
Revises: 698d6b1f9692
Create Date: 2025-02-26 22:51:43.374391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4723b1c10c01'
down_revision = '698d6b1f9692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.drop_column('file_extension')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('summary')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('file_extension', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
