"""Added filepost db model to help with sending chronological file list

Revision ID: 698d6b1f9692
Revises: ec79001bac21
Create Date: 2025-02-26 20:52:34.364586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698d6b1f9692'
down_revision = 'ec79001bac21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('file_extension', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_extension')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
