"""Initial migration

Revision ID: 8afc7155f42d
Revises: 
Create Date: 2024-06-07 19:05:43.942028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afc7155f42d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.drop_column('total_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rating', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
