"""Added case_category to caselog

Revision ID: ec79001bac21
Revises: 
Create Date: 2025-02-26 14:17:53.310037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79001bac21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caselog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_category', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caselog', schema=None) as batch_op:
        batch_op.drop_column('case_category')

    # ### end Alembic commands ###
